import type { NextPage } from "next";
import Head from "next/head";
import Home from "./home";

const Index: NextPage = () => (
	<div>
		<Head>
			<title>ESPRIT</title>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<Home />
	</div>
);

export default Index;
